### PR TITLE
Add GTFS-realtime support

### PR DESCRIPTION
**Pull request by minhhpham**
The main difference between the main branch and this branch is that the former collects and processes data from the [NextBus API](https://www.nextbus.com/xmlFeedDocs/NextBusXMLFeed.pdf) while the later processes data from archived GTFS-Realtime data. Another major difference is that after creating Retro-GTFS packages for each day, this program will combine the daily packages into one package via one of the two methods:
- Taking the average of `arrival_time`'s and the average of `departure_time`'s, grouped by `trip_id` and `stop_sequence` (check [stop_times.txt](https://developers.google.com/transit/gtfs/reference/#stop_timestxt)). 
- Retaining all trips by modifying the `trip_id` from all days and using [calendar_dates.txt](https://developers.google.com/transit/gtfs/reference/#calendar_datestxt) instead of [calendar.txt](https://developers.google.com/transit/gtfs/reference/#calendartxt). This is a practice in GTFS that omits [calendar.txt](https://developers.google.com/transit/gtfs/reference/#calendartxt), and specify each date of service in [calendar_dates.txt](https://developers.google.com/transit/gtfs/reference/#calendar_datestxt) to allow for considerable service variation and accommodates service without normal weekly schedules. Taking the image below as an example, the first two tables show the results of the same trip on 05/18/2018 and 05/19/2018, and how they are combined in the aggregated file presented in the third table. 
image
And the [calendar_dates.txt](https://developers.google.com/transit/gtfs/reference/#calendar_datestxt) would look like:
image

### CODE REVIEW

**Comment by barbeau** [comment]
@minhhpham Thanks!

A few requests:
1. It looks like there are some whitespace issues in the PR - many files look like they are deleted and re-added entirely, versus just smaller line-by-line changes.  Could you please try to remove the whitespace (e.g., line endings) changes so we can just review the code differences? **EDIT** Minh found this was a good solution - https://stackoverflow.com/a/4683783/937715
1. How are the GTFS-rt server details configured?  I looked at `sample_conf.py` but I don't see an obvious place to put the info.

**Comment by minhhpham** [comment]
The main difference between the main branch and this branch is that the former collects and processes data from the [NextBus API](https://www.nextbus.com/xmlFeedDocs/NextBusXMLFeed.pdf) while the later processes data from archived GTFS-Realtime data. Another major difference is that after creating Retro-GTFS packages for each day, this program will combine the daily packages into one package via one of the two methods:
- Taking the average of `arrival_time`'s and the average of `departure_time`'s, grouped by `trip_id` and `stop_sequence` (check [stop_times.txt](https://developers.google.com/transit/gtfs/reference/#stop_timestxt)). 
- Retaining all trips by modifying the `trip_id` from all days and using [calendar_dates.txt](https://developers.google.com/transit/gtfs/reference/#calendar_datestxt) instead of [calendar.txt](https://developers.google.com/transit/gtfs/reference/#calendartxt). This is a practice in GTFS that omits [calendar.txt](https://developers.google.com/transit/gtfs/reference/#calendartxt), and specify each date of service in [calendar_dates.txt](https://developers.google.com/transit/gtfs/reference/#calendar_datestxt) to allow for considerable service variation and accommodates service without normal weekly schedules. Taking the image below as an example, the first two tables show the results of the same trip on 05/18/2018 and 05/19/2018, and how they are combined in the aggregated file presented in the third table. 
image
And the [calendar_dates.txt](https://developers.google.com/transit/gtfs/reference/#calendar_datestxt) would look like:
image

**Comment by minhhpham** [comment]
Regarding the GTFS-RT server configuration, there is a parameter named `API_URL` in `sample_conf.py`. This is the URL to the GTFS-RT server. I used the [Transi project](https://gitlab.com/cutr-at-usf/transi/getting-started) as a GTFS-RT server. All API calls to the server are hard coded according to the [Transi project](https://gitlab.com/cutr-at-usf/transi/getting-started). One can modify the code to work with their own GTFS-RT server or to work with GTFS-RT files from disk. The instruction to do so is in `README.md`.

**Comment by barbeau** [comment]
Closing this in favor of the PR upstream at https://github.com/CUTR-at-USF/retro-gtfs/pull/1.

**Pull request closed without merging**
